stages:
- stage: test
  jobs:
    - job: codecov
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn test:ci -t $(CODECOV_TOKEN)

- stage: build
  jobs:
    - job: Linux
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn build
        displayName: 'yarn install and build'

    - job: Windows
      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - powershell: |
          yarn install --frozen-lockfile
          yarn build
        displayName: 'yarn install and build'

    - job: website
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn docs:build

      - publish: $(System.DefaultWorkingDirectory)/docs/dist
        artifact: website

- stage: publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: artifact
      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - powershell: |
          yarn install --frozen-lockfile
        displayName: 'yarn install'

      - powershell: |
          npm version prerelease
        displayName: 'version bump'

      - publish: $(System.DefaultWorkingDirectory)
        artifact: vuent-all

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: |
            dist/*
            README.md
            LICENSE
            package.json
          targetFolder: '$(Build.ArtifactStagingDirectory)'
          overWrite: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: vuent
