stages:
- stage: test
  jobs:
    - job: unit
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn test:ci -t $(CODECOV_TOKEN)

- stage: build
  jobs:
    - job: Linux
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn build
        displayName: 'yarn install and build'

    - job: Windows
      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - powershell: |
          yarn install --frozen-lockfile
          yarn build
        displayName: 'yarn install and build'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: |
            dist/*
            README.md
            LICENSE
            package.json
          targetFolder: '$(Build.ArtifactStagingDirectory)'
          overWrite: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: vuent

    - job: website
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          yarn install --frozen-lockfile
          yarn docs:build

      - publish: $(System.DefaultWorkingDirectory)/docs/dist
        artifact: website

- stage: prerelease
  # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: artifact
      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - powershell: |
          yarn install --frozen-lockfile
          yarn build
        displayName: 'yarn install and build'

      - powershell: |
          npm --no-git-tag-version version prerelease --preid=$(Build.BuildId)
        displayName: 'version bump'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: |
            dist/*
            README.md
            LICENSE
            package.json
          targetFolder: '$(Build.ArtifactStagingDirectory)/artifact'
          overWrite: true

      - publish: $(Build.ArtifactStagingDirectory)/artifact
        artifact: vuent_next
