# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true

    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test:ci 
    - run: yarn build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: vuent
        path: |
          dist
          README.md
          CHANGELOG.md
          LICENSE
          package.json
          
  storybook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      env:
        CI: true

    - run: yarn install --frozen-lockfile
    - run: yarn storybook:build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: storybook
        path: storybook-static
          
  website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      env:
        CI: true

    - run: yarn install --frozen-lockfile
    - run: yarn docs:build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: website
        path: docs/dist
          
